2020-03-03 09:56:32,870 - werkzeug - INFO -  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2020-03-03 09:57:51,878 - werkzeug - INFO -  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2020-03-03 09:58:07,989 - werkzeug - INFO - 127.0.0.1 - - [03/Mar/2020 09:58:07] "[33mGET / HTTP/1.1[0m" 404 -
2020-03-03 09:58:08,152 - werkzeug - INFO - 127.0.0.1 - - [03/Mar/2020 09:58:08] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2020-03-03 09:58:14,623 - file - DEBUG - TEST
2020-03-03 09:58:14,623 - werkzeug - INFO - 127.0.0.1 - - [03/Mar/2020 09:58:14] "[37mGET /test HTTP/1.1[0m" 200 -
2020-03-03 09:58:18,763 - file - ERROR - ERROR
2020-03-03 09:58:18,764 - application - ERROR - Exception on /error [GET]
Traceback (most recent call last):
  File "/Users/jamesbeedy/scania_demos/LMA/demo-flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jamesbeedy/scania_demos/LMA/demo-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jamesbeedy/scania_demos/LMA/demo-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jamesbeedy/scania_demos/LMA/demo-flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jamesbeedy/scania_demos/LMA/demo-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jamesbeedy/scania_demos/LMA/demo-flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "application.py", line 31, in error
    return "a" / 2
TypeError: unsupported operand type(s) for /: 'str' and 'int'
2020-03-03 09:58:18,768 - werkzeug - INFO - 127.0.0.1 - - [03/Mar/2020 09:58:18] "[35m[1mGET /error HTTP/1.1[0m" 500 -
